#
# Copyright 2020 Adobe
# All Rights Reserved.
#
# NOTICE: Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying
# it. If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#

#
# This is the theme configuration
# Allowed configuration in a theme is (currently):
# params (global and per language)
# menu (global and per language)
# outputformats and mediatypes

[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
fuseSearch = true
# Search type can be one of 'fuse', 'stork'
searchType = "fuse"

